version: '3.9'

services:
  postgres:
    image: postgres:17
    container_name: lab4-postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - wildfly_data:/var/lib/postgresql/data
    restart: always
    shm_size: 128mb
    networks:
      - lab4-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  flyway:
    image: flyway/flyway:10.0.0
    command:
      - -url=jdbc:postgresql://postgres:5432/${DB_NAME:-lab4db}
      - -user=${DB_USERNAME:-postgres}
      - -password=${DB_PASSWORD:-postgres}
      - -connectRetries=10
      - -locations=filesystem:/flyway/sql
      - migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - lab4-network

  wildfly:
    build:
      context: .
      args:
        - DATABASE_URL=${DATABASE_URL}
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
        - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    container_name: lab4-wildfly
    ports:
      - "8080:8080"
      - "9990:9990"
    restart: unless-stopped
    depends_on:
      flyway:
        condition: service_completed_successfully
    networks:
      - lab4-network

networks:
  lab4-network:
    external: true
    name: lab4-network

volumes:
  wildfly_data:
  wildfly_config:
