name: Build, Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-on-server:
    runs-on: ubuntu-latest
    
    steps:    
    - name: Stop and deploy
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "Starting deployment"

          cd ~/lab4/backend

          docker-compose down || true

          git pull

          docker-compose up -d --build

          echo "Finish deployment"
